name: tatarupiah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: 1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.66.2
  flutter_switch: ^0.3.2
  gap: ^3.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/icons/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true

