name: tatarupiah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  get_cli: 1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.18.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.66.2
  flutter_switch: ^0.3.2
  gap: ^3.0.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  logger: ^2.2.0
  email_validator: ^2.1.17
  skeletonizer: ^1.3.0
  lottie: ^3.1.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/icons/
    - assets/icons/packs/
    - assets/images/
    - assets/animations/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true

