name: tatarupiah
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.66.2
  flutter_switch: ^0.3.2
  gap: ^3.0.1
  rive: ^0.13.1
  chat_gpt_sdk: ^3.0.9
  percent_indicator: ^4.2.3
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  logger: ^2.2.0
  email_validator: ^2.1.17
  skeletonizer: ^1.3.0
  lottie: ^3.1.2
  syncfusion_flutter_datepicker: ^26.1.39
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  device_preview: ^1.2.0
  flutter_intro: ^3.2.3
  connectivity_plus: ^6.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  assets: 
    - assets/icons/
    - assets/icons/packs/
    - assets/images/
    - assets/animations/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true

