import 'package:get/get.dart';

mixin IconMixin on GetxController {
  List iconPacks = [
    'assets/icons/packs/car.svg',
    'assets/icons/packs/motorcycle.svg',
    'assets/icons/packs/airplane.svg',
    'assets/icons/packs/ship.svg',
    'assets/icons/packs/fertilizer.svg',
    'assets/icons/packs/fork.svg',
    'assets/icons/packs/rice.svg',
    'assets/icons/packs/noodle.svg',
    'assets/icons/packs/pizza.svg',
    'assets/icons/packs/soup.svg',
    'assets/icons/packs/sushi.svg',
    'assets/icons/packs/bread.svg',
    'assets/icons/packs/drink.svg',
    'assets/icons/packs/cofee.svg',
    'assets/icons/packs/cup.svg',
    'assets/icons/packs/soda.svg',
    'assets/icons/packs/icecream.svg',
    'assets/icons/packs/money.svg',
    'assets/icons/packs/bank.svg',
    'assets/icons/packs/pig.svg',
    'assets/icons/packs/shop-bag.svg',
    'assets/icons/packs/game.svg',
    'assets/icons/packs/voucher.svg',
    'assets/icons/packs/education.svg',
    'assets/icons/packs/health.svg',
    'assets/icons/packs/medicine.svg',
    'assets/icons/packs/repair.svg',
    'assets/icons/packs/house.svg',
    'assets/icons/packs/document.svg',
  ].obs;
}